# Generated by Django 4.2.5 on 2023-09-30 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConfigurationName', models.CharField(max_length=100)),
                ('TelegramToken', models.CharField(max_length=100)),
                ('BotStatus', models.BooleanField(default=False)),
                ('AngleOneUserName', models.CharField(max_length=100)),
                ('AngleOnePassword', models.CharField(max_length=100)),
                ('AngleOneApiKey', models.CharField(max_length=100)),
                ('AngleOneTotp', models.CharField(max_length=100)),
                ('AngleOneClientId', models.CharField(max_length=100)),
                ('AngleOneClientPin', models.CharField(max_length=100)),
                ('AngleOneFeedToken', models.CharField(blank=True, max_length=100, null=True)),
                ('AngleOneObj', models.CharField(blank=True, max_length=100, null=True)),
                ('ImgToTextApiLayer', models.CharField(max_length=100)),
                ('Palm2Api', models.CharField(max_length=100)),
                ('Palm2Model', models.CharField(max_length=100)),
                ('NgrokBaseUrl', models.CharField(max_length=100)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('NormalBalance', models.FloatField(default=0.0)),
                ('HeroZeroBalance', models.FloatField(default=0.0)),
                ('ForcedExitWithoutSelling', models.BooleanField(default=False)),
                ('ForcedExitWithSelling', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderSymbol', models.CharField(max_length=100)),
                ('OrderStatus', models.BooleanField(default=False)),
                ('StrategyCode', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-CreatedDate'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StrategyName', models.CharField(max_length=100)),
                ('StrategyCode', models.CharField(max_length=255)),
                ('StrategyDescription', models.TextField(blank=True, null=True)),
                ('SL', models.FloatField()),
                ('TGT', models.FloatField(blank=True, null=True)),
                ('HalfQtyBookAt', models.FloatField(blank=True, null=True)),
                ('TrailingMargin', models.FloatField(blank=True, null=True)),
                ('TrailingStartAt', models.FloatField(blank=True, null=True)),
                ('LotCondition', models.IntegerField(blank=True, null=True)),
                ('LtpCondition', models.FloatField(blank=True, null=True)),
                ('StrategyStatus', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
                'ordering': ['-StrategyStatus'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionSymbol', models.CharField(max_length=100)),
                ('BuySell', models.CharField(max_length=100)),
                ('TransactionLotSize', models.IntegerField()),
                ('TransactionLot', models.IntegerField()),
                ('TriggerPrice', models.FloatField()),
                ('TriggerTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('OrderObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.order')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-TriggerTime'],
            },
        ),
    ]
