# Generated by Django 4.2.5 on 2023-09-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='StrategyCode',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
