# Generated by Django 4.2.5 on 2023-09-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_strategy_strategycode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='AngleOneObj',
            new_name='AngleOneAccessToken',
        ),
        migrations.AddField(
            model_name='configuration',
            name='AngleOneRefreshToken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='AngleOneUserId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
