# Generated by Django 4.2.5 on 2023-10-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_lotcondition_strategy_lotconditiong_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name': 'Strategy', 'verbose_name_plural': 'Strategies'},
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='HalfQtyBookAt',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='LotConditionG',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='LotConditionL',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='LtpCondition',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='StrategyStatus',
        ),
        migrations.AddField(
            model_name='configuration',
            name='ActiveStrategyCodeFor0T1',
            field=models.CharField(default='SLTGT', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='ActiveStrategyCodeFor0TAll',
            field=models.CharField(default='SLTGT', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='HeroZeroStatus',
            field=models.BooleanField(default=False),
        ),
    ]
