# Generated by Django 4.2.5 on 2023-10-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_strategy_options_remove_strategy_halfqtybookat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='AngleOneAccessToken',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='AngleOneRefreshToken',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='AngleOneUserId',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
