# Generated by Django 4.2.5 on 2023-10-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_configuration_angleoneaccesstoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='TokenUpdatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
