# Generated by Django 4.2.5 on 2023-10-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_configuration_tokenupdateddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
