# Generated by Django 4.2.5 on 2023-10-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_order_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strategy', models.CharField(max_length=100)),
                ('BUYINGPRICE', models.FloatField()),
                ('LTP', models.FloatField()),
                ('T_TGT', models.FloatField()),
                ('SL', models.FloatField()),
                ('TGT', models.FloatField()),
                ('Returns', models.FloatField()),
                ('PNL', models.FloatField()),
                ('running', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
    ]
