# Generated by Django 4.2.5 on 2023-10-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_remove_livedb_sl_remove_livedb_tgt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedb',
            name='SL',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
