# Generated by Django 4.2.5 on 2023-10-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_livedb_sl'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='FakeLTPStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livedb',
            name='FakeLTP',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
