# Generated by Django 4.2.5 on 2023-10-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_configuration_fakeltpstatus_livedb_fakeltp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livedb',
            name='FakeLTP',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
    ]
